import os
from bs4 import BeautifulSoup

# CONFIGURATION
ROOT_DIR = "."
# This CSS hides the website "fluff" and focuses on the content for the PDF
PRINT_CSS = """
@media print {
    /* 1. Hide Non-Essential Elements */
    nav, footer, aside, .hero, #related-sidebar, .pinterest-btn, #weather-widget, .ad-slot {
        display: none !important;
    }
    
    /* 2. Hide Buttons (Calculate, Save, Print) so they don't appear on paper */
    button, .btn, input[type="submit"], .fa-solid, .fa-regular, .fa-brands {
        display: none !important;
    }

    /* 3. Reset Layout for Paper */
    body, section, article, .max-w-7xl, .lg\\:col-span-9 {
        width: 100% !important;
        max-width: 100% !important;
        margin: 0 !important;
        padding: 0 !important;
        background: white !important;
        box-shadow: none !important;
        display: block !important;
    }

    /* 4. Style the Result Box for Print */
    /* We try to target common result container classes */
    #result, .result-box, .bg-emerald-50, .bg-blue-50 {
        border: 2px solid #334155 !important;
        background-color: #fff !important;
        color: #000 !important;
        padding: 20px !important;
        margin-top: 20px !important;
        border-radius: 8px !important;
    }

    /* 5. Add a Pro Footer */
    body::after {
        content: "Report Generated by RenoCalcHub.com";
        display: block;
        text-align: center;
        color: #94a3b8;
        font-size: 10pt;
        margin-top: 50px;
        border-top: 1px solid #e2e8f0;
        padding-top: 10px;
    }
}
"""

def inject_print_styles(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            html = f.read()

        soup = BeautifulSoup(html, "html.parser")
        
        if not soup.head:
            print(f"⚠️ Skipping {filepath}: No <head> tag found.")
            return

        # Check if we already added print styles to avoid duplicates
        # We look for a style tag containing "@media print"
        existing_styles = soup.head.find_all("style")
        for style in existing_styles:
            if "@media print" in style.decode_contents():
                print(f"⏩ Already has Print CSS: {filepath}")
                return

        # Create the new style tag
        new_style = soup.new_tag("style")
        new_style.string = PRINT_CSS
        
        # Append to the end of <head>
        soup.head.append(new_style)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(str(soup.prettify()))
            
        print(f"✅ Injected Print CSS: {filepath}")

    except Exception as e:
        print(f"❌ Error processing {filepath}: {e}")

def main():
    print("--- Injecting Print-to-PDF Styles ---")
    for root, dirs, files in os.walk(ROOT_DIR):
        # Skip system folders
        if "css" in dirs: dirs.remove("css")
        if "js" in dirs: dirs.remove("js")
        if ".git" in dirs: dirs.remove(".git")
        
        if "index.html" in files:
            inject_print_styles(os.path.join(root, "index.html"))

if __name__ == "__main__":
    main()